services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: