services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - .env.development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: